Add "SOL for testing networks" guide
solana-foundation/developer-content pull request #13
Opened 2023-07-28 22:34 UTC by valentinmadrid

2023-08-08 18:01 UTC, nickfrosty requested changes
Since the route for this guide on Solana.com is determined by the file name and location within this content repo, can you change the file to be located at `content/guides/getstarted/solana-token-airdrop-and-faucets.md`

This will result in the guide being available at solana.com/developers/guides/getstarted/solana-token-airdrop-and-faucets

2023-08-10 10:40 UTC, valentinmadrid commented on content/guides/faucets/airdrop-development-sol.md
> +# **SOL for Solana Testing Networks**
is it right to say Tokens here ?

2023-08-10 11:14 UTC, valentinmadrid commented on content/guides/faucets/airdrop-development-sol.md
> +**Using a web faucet:**
The thing is that solfaucet uses connection.requestAirdrop() under the hood, which would be the same method as the other ones in that category. faucet.solana.com is transferring SOL instead.

2023-08-10 11:22 UTC, valentinmadrid commented on content/guides/faucets/airdrop-development-sol.md
> +_The POW Faucet is maintained by Ellipsis Labs_
I added it to to the `POW Faucet` name, think that fits better

2023-08-10 11:29 UTC, valentinmadrid commented
Should be good, please take a look at the two comments I wrote.

2023-08-10 18:59 UTC, nickfrosty commented on content/guides/faucets/airdrop-development-sol.md
> +# **SOL for Solana Testing Networks**
It mostly semantics. In general for SEO, the "SOL tokens" phrasing will likely perform better in search engines since that is what people search for

2023-08-10 19:01 UTC, valentinmadrid commented on content/guides/faucets/airdrop-development-sol.md
> +**Using a web faucet:**
https://faucet.solana.com uses a regular system Program transfer instruction. I'm not sure if it's needed to add the regular requestAirdrop() to it, please let me know if you think so.
We can also remove the solfaucet.com link from the guide if we add regular airdrops to faucet.solana.com

2023-08-10 19:03 UTC, nickfrosty commented on content/guides/faucets/airdrop-development-sol.md
> +**Using a web faucet:**
Let's do that:
1. add regular airdrop to faucet.solana.com
2. remove solfaucet.com

2023-08-11 17:29 UTC, nickfrosty approved these changes

2023-08-11 17:29 UTC, merged

2023-08-11 17:32 UTC, nickfrosty commented
This guide was published to: https://solana.com/developers/guides/getstarted/solana-token-airdrop-and-faucets