add: getting started on solana intro
solana-foundation/developer-content pull request #195
Opened 2024-05-01 06:06 UTC by jacobcreech

2024-05-01 06:06 UTC, jacobcreech commented on docs/intro/dev.md
> +![A view of how clients work with the Solana blockchain](/assets/guides/intro/developer_flow.png)
Not a blocker imo but I'm asking Hovin to make a nice picture of this

2024-05-01 14:08 UTC, nickfrosty requested changes
We can go back and update the graphic later after Hovin creates it too

2024-05-01 17:07 UTC, jacobcreech commented on docs/intro/dev.md
> +  framework built in Python or Typescript
Ah, it got moved under solders with the same module name https://github.com/kevinheavey/solders

2024-05-01 19:05 UTC, mikemaccana requested changes
Excellent, this includes so many things I wish I had known when getting started on Solana, like the local validator and how similar Solana development is to traditional backend/frontend work. 

Most of these fixes are just minor English bits and some terminology consistency fixes. Also I'm not totally sure on how well C / C++ is maintained compared to Rust - if it's just as good, great, if not I think we should just point people to Rust. Changes are done as suggestions so you can just click the button if you agree.

2024-05-01 19:05 UTC, mikemaccana commented on docs/intro/dev.md
```suggestion
The best support you can find is on [Solana StackExchange](https://solana.stackexchange.com/). Search for your question there first - there's a good chance there will already be a question asked by someone else, with an answer. If it's not there, add a new question! Remember to include as much detail as you can in your question, and please use text (not screenshots) to show error messages, so other people with the same problem can find your question!

```

2024-05-01 19:05 UTC, mikemaccana commented on docs/intro/dev.md
Just a suggestion. Maybe this is too much detail. WDYT?

2024-05-01 19:05 UTC, mikemaccana commented on public/assets/docs/intro/developer_flow.png
I'd re-do this in Whimsical, should only take a moment.

2024-05-01 19:13 UTC, jacobcreech commented on docs/intro/dev.md
> +   or C++.
Worth mentioning, but we should have a recommendation to use Rust as the best maintained.

2024-05-01 19:26 UTC, jacobcreech commented on public/assets/docs/intro/developer_flow.png
Getting an updated version from Hovin. Solana-themed

2024-05-01 21:55 UTC, jacobcreech commented
All comments should be addressed now

2024-05-02 13:15 UTC, nickfrosty approved these changes
I fixed a few last minute types from the recent changes, but the rest is great!

2024-05-02 13:16 UTC, merged