cash app guide
solana-foundation/developer-content pull request #212
Opened 2024-05-13 14:48 UTC by brimigs

### Summary of Changes

Add tutorial for a web3 cash app

2024-05-13 21:06 UTC, mikemaccana requested changes
Awesome ✨. Love having mobile apps and we should be doing more guides with domain names like this. This PR feedback looks like a lot, but it's nearly all suggestions (you can just click 'accept' if you like them) or find/replace jobs. Once they're sorted we can get this published ASAP! 🎉

2024-05-13 21:06 UTC, mikemaccana commented on content/guides/dapps/cash-app.md
> +address. By implementing SNS, we can easily prompt a user to create a user name
Feel bad mentioning this but SNS isn't the only name service on Solana and we probably shouldn't be seen to endorse them per CONTRIBUTING. How do we want to handle this? A good compromise might be 

> This demo uses Bonfida's `.sol` name but there's many name services on Solana including AllDomains (`.bonk`, `.solana` etc).

Maybe that's not enough? @nickfrosty WDYT?

2024-06-13 05:24 UTC, jacobcreech requested changes
Awesome job on this guide. Just a few nits. Let's get those programs into program-examples to update all the links and ship this guide!

2024-06-13 05:24 UTC, jacobcreech commented on content/guides/dapps/cash-app.md
> +        cash_account.friends.push(pubkey);
It would be good to note the limitations of this design. Vec can only grow to so many friends.

2024-06-13 05:24 UTC, jacobcreech commented on content/guides/dapps/cash-app.md
> +Now your Solana program should match the final version here: /// FIX ME: Add
Reminder for `FIX ME`

2024-06-13 05:24 UTC, jacobcreech commented on content/guides/dapps/cash-app.md
> +that of a web2 application.
Any closing thoughts? A congratulations to the reader for making it this far and building their first mobile app?

2024-07-18 21:32 UTC, jacobcreech approved these changes

2024-07-18 21:33 UTC, merged