Test validator guide
solana-foundation/developer-content pull request #213
Opened 2024-05-14 17:27 UTC by brimigs

Update solana-test-validator docs

2024-05-22 18:02 UTC, nickfrosty requested changes
Great guide, just nits and questions

2024-06-06 05:59 UTC, jacobcreech requested changes

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +[already installed](http://localhost:3000/developers/guides/getstarted/setup-local-development#3-install-the-solana-cli),
You'll have to change this link to be just the context instead of localhost

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +your desired release (i.e. `v1.18.1`), or use one of the three symbolic channel
```suggestion
your desired release (i.e. `v1.18.12`), or use one of the three symbolic channel
```

Just to put a release that works

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +Check CLI Tool Suite configuration:
Agreed, this is extraneous info

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +First, save the desired state of an account as a JSON file:
Could we give an example of doing this with a USDC account?

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +## Interacting with a Running Test Validator
Imo this section should come first after installation. Get the developer doing useful stuff asap, then teach them how to properly configure everything later.

2024-06-06 05:59 UTC, jacobcreech commented on content/guides/getstarted/solana-test-validator.md
> +solana account <ACCOUNT_ADDRESS>
If you do airdrop before `solana account X` you can view the details of the account. If you do before, the account will not exist.

2024-06-13 04:00 UTC, jacobcreech approved these changes
Awesome work!

2024-06-13 04:02 UTC, merged