Migrate Unboxed repo modules into courses
solana-foundation/developer-content pull request #250
Opened 2024-06-28 19:05 UTC by mikemaccana

- Moved course-structure from https://github.com/Unboxed-Software/solana-course/pull/384 to this repo using metadata.yml files
  - The "extending-solana-functionality" section was split into "connecting to offchain data" course and a separate "solana pay" single-lesson course.
  - 'versioned-transaction' was renamed to 'lookup-tables'
  - 'env-variables' was renamed to 'program configuration'
  - Tweak the Anchor CPI text to avoid assuming people have read the native CPI lesson.
  - Re-add burning and delegation exercises in a new lesson and lab
- Fix internal relative links to the other lessons
- Added images and fixed image links
- Changed any link text that includes '//' to work around an apparent bug in https://github.com/remarkjs/remark-gfm
- Add descriptions for all lessons
- Use Callouts for tips
- Remove a few remaining instances of old airtable form

2024-07-01 20:54 UTC, mikemaccana commented
Getting:

> `Error: Static page generation for /en/environment is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout` 

- which doesn't seem related to this work.

2024-07-01 20:58 UTC, mikemaccana commented
Gettimg:

> Build error occurred
> Error: Static page generation for /en/environment is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout

Which doesn't seem related to this work 🤔

2024-07-16 16:56 UTC, nickfrosty requested changes
I rebased with master already for this PR :) and fixed a lingering import from contentlayer1

I also left a few assorted typo comments throughout. But I stopped looking for those since there are lots.... I was just flagged the ones that my editor would flag to me. We should fix those

some of the code blocks are REALLY big. I think we should use the `details` approach that John Liu recently started using with some of his content PRs (this can be seperate PRs to help tidy things later)

Important fixes right now:
- update all relative links (i.e. `./file`). they do not work in this repo
- the "Onchain program development" course seems wholly focused on Anchor, but it is not clear from the metadata
- the `security-intro` lesson has no heading on the page's content, so it looks really odd on solana-com. can you add some headings that make sense?
- for the form link displayed at the end, you could wrap it in a "success" Callout to make it stand out some more. but if not, that's cool too

2024-07-16 16:56 UTC, nickfrosty commented on content/courses/native-development/metadata.yml
> +title: Native onchain program development
can we update the slug for this course to be `native-onchain-development`

2024-07-16 17:25 UTC, mikemaccana commented on content/courses/intro-to-solana/intro-to-custom-onchain-programs.md
> +[Intro to Writing Data](./intro-to-writing-data).
Done

2024-07-16 17:27 UTC, mikemaccana commented on content/courses/mint-extensions/metadata.yml
> +title: Token Extensions for Mints
100% that's way better.

2024-07-16 18:03 UTC, mikemaccana commented
> update all relative links (i.e. ./file). they do not work in this repo ✅
> Mentioned Anchor in "Onchain program development" metadata ✅
> Added missing heading (to security-intro) plus some lesson -> course fixes  ✅
> Wrap the form link in a "success" Callout to make it stand out some more  ✅

2024-07-17 15:25 UTC, nickfrosty approved these changes

2024-07-17 15:25 UTC, merged