Added hints, updated versions and added js client
solana-foundation/developer-content pull request #286
Opened 2024-08-01 11:25 UTC by Woody4618

### Problem
While going through our hello world user tests some problems emerged. 

### Summary of Changes
Some of these are tackled in this PR. For example adding a link to the solana web faucet, adding solutions for some pit falls  and updating everything to the newest versions. 

Also added a JS client to the hello world guide to be able to call the program in the end for a nice little success.

2024-08-02 14:58 UTC, mikemaccana approved these changes
A couple of minor suggestions but looks fine.

2024-08-02 14:58 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +system. Type the following command in your Windows power shell:
```suggestion
system. Type the following command in Windows PowerShell:
```

2024-08-02 14:58 UTC, mikemaccana commented on content/guides/getstarted/local-rust-hello-world.md
> +> Don't forget to replace `YOUR_PROGRAM_ID` with the program id you got from the
```suggestion
> Don't forget to replace `YOUR_PROGRAM_ID` with the program ID you got from the
```

2024-08-02 20:22 UTC, nickfrosty requested changes
Nice additions, just some small typo fixes

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/setup-local-development.md
> +> cd <your username>
In unix system, the user can nagivate to their home directory using the `~` path:

```suggestion
> cd ~
```

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/setup-local-development.md
> +[guide](https://solana.com/de/developers/guides/getstarted/solana-token-airdrop-and-faucets)
```suggestion
also get your
wallet address using `solana address` and request testing SOL on the
[Solana Web Faucet](https://faucet.solana.com). If you ever need bigger amounts
you can find ways to do so in this
[guide](/content/guides/getstarted/solana-token-airdrop-and-faucets.md)
```

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/local-rust-hello-world.md
> +  - windows
this does not matter for keywords

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/local-rust-hello-world.md
> +> and then run `cargo build-sbf` again.
typo fix:
```suggestion
> may need to go to `~/.cache/solana/` and `rm -rf` the platform tools there and
> then run `cargo build-sbf` again.
```

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/local-rust-hello-world.md
> +npm install @solana-developers/helpers
you can install multiple packages using the same line:
```suggestion
npm install @solana/web3.js @solana-developers/helpers
```

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/local-rust-hello-world.md
> +## Deploy to solana devnet
```suggestion
## Deploy to Solana devnet
```

2024-08-02 20:22 UTC, nickfrosty commented on content/guides/getstarted/local-rust-hello-world.md
> +`https://api.devnet.solana.com` and run the client again.
```suggestion
Then change the connections url in your `client.mjs` also to
`https://api.devnet.solana.com` and run the client again.
```

2024-08-05 14:19 UTC, nickfrosty approved these changes
Thanks for these updates Jonas :)

2024-08-05 14:19 UTC, merged