Fix dead link in hello-world-in-your-browser.md
solana-foundation/developer-content pull request #33
Opened 2023-12-07 22:15 UTC by MacroChip

2023-12-07 22:51 UTC, nickfrosty requested changes
Great catch on this! But a better way is the absolute path within this repo. It will allow people to navigate to the file while exploring this repo, and on the respective page on solana.com/developers/guides/*

While you already have this PR open, can you fix the other `./*` links within this file?

2023-12-07 22:51 UTC, nickfrosty commented on content/guides/getstarted/hello-world-in-your-browser.md
> +- [Setup your local development environment](https://solana.com/developers/guides/getstarted/setup-local-development)
Great catch on this!

```suggestion
- [Setup your local development environment](/content/guides/getstarted/setup-local-development.md)
```

2023-12-09 20:46 UTC, MacroChip commented
I think that's it. Fyi I couldn't get next running properly locally to fully verify but I believe it's correct. The links were working properly in vscode.

2023-12-12 20:04 UTC, nickfrosty commented
> I think that's it. Fyi I couldn't get next to compile the app properly to fully verify but I believe it's correct. The links were working properly in vscode.

what was the error you were getting when you tried to build it?
or are you referring to the GitHub action for `vercel` not completing?

2023-12-15 19:23 UTC, merged

2023-12-15 19:24 UTC, nickfrosty commented
Thanks for the updates here! There was recently a huge docs migration merge into `main`, so I fixed the links for those changes

2023-12-21 06:20 UTC, MacroChip commented
Very sorry I missed this notification. Build is working fine for me now! I don't remember what was happening.