refactor: optimize counter increment logic and notification handling
solana-foundation/developer-content pull request #355
Opened 2024-08-27 04:26 UTC by EmekaManuel

### Problem
- The showToastOrAlert function name was unclear, and error handling in async functions was inconsistent.
- The logic for balance checks and airdrop requests during transactions needed improvements.
- Detailed error logging and cleanup were required for better readability and maintainability.

### Summary of Changes
Refactored showToastOrAlert to showNotification for better clarity.
Improved async/await usage with consistent error handling using try/catch.
Added detailed logging for missing program or counterAddress.
Cleaned up and grouped logic for better readability and maintainability.
Ensured balance checks and airdrop requests are well-handled during transactions.

2024-08-27 18:01 UTC, mikemaccana commented
Thanks! Needs a little work but we can get this in once done.

2024-08-27 19:13 UTC, EmekaManuel commented
> Thanks! Needs a little work but we can get this in once done.

Thank you Mike! Looking forward to that.

2024-09-04 19:46 UTC, mikemaccana requested changes
Some small changes needed but also not many.

2024-09-04 20:21 UTC, EmekaManuel commented on content/courses/mobile/intro-to-solana-mobile.md
> +        program: !!program ? "Program Loaded" : "Program Not loaded",
fixed !

2024-09-04 20:21 UTC, EmekaManuel commented on content/courses/mobile/intro-to-solana-mobile.md
> +      : Alert.alert(message);
fixed !

2024-09-04 20:25 UTC, EmekaManuel commented on content/courses/mobile/intro-to-solana-mobile.md
> +  const showNotification = (message: string) => {
this does show notification. can you please elaborate on this review

2024-09-06 02:23 UTC, mikemaccana commented on content/courses/mobile/intro-to-solana-mobile.md
> +  const showNotification = (message: string) => {
Does it create one of these?

![image](https://github.com/user-attachments/assets/c45090d6-22cd-4904-94db-bddb0727aed3)

2024-09-06 02:24 UTC, mikemaccana requested changes
Just one last bit and we can get this in.

2024-09-06 07:41 UTC, EmekaManuel commented on content/courses/mobile/intro-to-solana-mobile.md
> +  const showNotification = (message: string) => {
It creates these instead: 
![alert_example_ios](https://github.com/user-attachments/assets/20972d45-839c-4e42-9d3b-f2bfb7247884)
![alert_example_android](https://github.com/user-attachments/assets/feedf44b-018f-4a93-a2a9-b7c48c518ae6)

2024-09-12 21:04 UTC, mikemaccana commented on content/courses/mobile/intro-to-solana-mobile.md
> +  const showNotification = (message: string) => {
That's not a 'notification' then. The word notification has a very specific meaning on mobile. Please change the function name.

2024-09-12 21:06 UTC, mikemaccana requested changes
Just need to fix function name per above. `showMessage()` would be fine. Just not 'notification'.

2024-09-12 21:45 UTC, EmekaManuel commented on content/courses/mobile/intro-to-solana-mobile.md
> +  const showNotification = (message: string) => {
changed to showMessage()

2024-09-12 21:45 UTC, EmekaManuel commented
> Just need to fix function name per above. `showMessage()` would be fine. Just not 'notification'.

changed to showMessage✅

2024-12-12 00:17 UTC, closed without merging