[workflow]add workflow to check link validation
solana-foundation/developer-content pull request #370
Opened 2024-08-28 08:39 UTC by flingjie

**Problem:**

Some links may be invalid in the markdown files.

**Summary of Changes:**

- Added file check-links.yaml to .github/workflows.

**related issue**

https://github.com/solana-foundation/developer-content/issues/12

2024-08-28 17:19 UTC, mikemaccana commented
Hrm:

```
FILE: ./docs/index.md
...
  [✖] /docs/core/programs
```

But https://solana.com/docs/core/programs exists.  

_____

Separately: rather than listing what works, it's better to only list what has failed.

2024-08-28 17:22 UTC, mikemaccana requested changes
See comments above.

2024-08-29 06:04 UTC, flingjie commented
> This is a good idea! There seems to be some false positives though:
> 
> ```
> FILE: ./docs/index.md
> ...
>   [✖] /docs/core/programs
> ```
> 
> But https://solana.com/docs/core/programs exists. Do you know why this is?
> 
> Separately: rather than listing what works, it's better to only list what has failed. That allows us to scan test results and find failures very quickly.

The checker determines the validity of a link based on whether it can be accessed successfully. When it checks `/docs/core/programs`, it tries to visit `/docs/core/programs`, but this fails.

This behavior is inconsistent with the expected check of the address [https://solana.com/docs/core/programs](https://solana.com/docs/core/programs). 

I’ve added a configuration file that replaces links starting with `/ `with [https://solana.com/docs/core/](https://solana.com/docs/core/). For example, /`docs/core/programs` will be replaced with [https://solana.com/docs/core/programs](https://solana.com/docs/core/programs). This should give you the expected result.

 Also, I have set the checker to quiet mode, so it will only output the invalid links.

Is there anything else you’d like to configure? For example, ignore certain links...

2024-10-17 18:43 UTC, mikemaccana requested changes
Just following this up - can you please answer the comment in https://github.com/solana-foundation/developer-content/pull/370#issuecomment-2330509820c ?

2025-01-01 00:17 UTC, closed without merging