Updated security introduction lesson
solana-foundation/developer-content pull request #395
Opened 2024-08-30 03:16 UTC by 0xCipherCoder

### Problem
The security introduction lesson is updated.

### Summary of Changes

This structure ensures clarity and readability

Fixes #

2024-09-05 03:28 UTC, mikemaccana requested changes
A few changes, but mainly to old code, and I've added suggestions. Good work, fix the comments below and we can get this in quickly. There are two other entries for this lesson but this the most comprehensive, so you have a good chance to win.

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +in those lessons should help you avoid some common Solana exploits on your own.
```suggestion
understanding of security. Those courses should help you avoid some common Solana exploits on your own.
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +in those lessons should help you avoid some common Solana exploits on your own.
Nothing to do with your PR, we just need to fix this. All 40 lessons were originally in one giant course!

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +This module is designed to build on those lessons with two main goals:
```suggestion
This course builds on those courses with two main goals:
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +title: How to Approach the Program Security Module
```suggestion
title: How to Approach the Program Security Course
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +  - Understand how to approach the Program Security Module
```suggestion
  - Understand how to approach the Program Security Course
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +   secure.
```suggestion
2. Introduce you to the tools provided by Anchor to help keep your programs
   secure, and show native Rust users how to implement similar techniques on their own.  
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +If you completed the Basic Security lesson, the first few topics in this module
```suggestion
While the first few lessons in this course cover similar topics to the [Anchor course](some link here) or [Program Security lesson](/content/courses/native-onchain-development/program-security.md) in the [Native Course](link here), 
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +If you completed the Basic Security lesson, the first few topics in this module
Add but also fix these links.

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +you’ll encounter new types of attacks. We encourage you to explore all of them.
```suggestion
but as you progress,
you’ll encounter new types of attacks. We encourage you to explore all of them.
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +explore topics in the order that suits you best.
make this a callout https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#callout

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +explore topics in the order that suits you best.
```suggestion
Unlike the lessons in other courses, which are in order, you are welcome to explore these lessons in whatever order suits you best.
```

2024-09-05 03:28 UTC, mikemaccana commented on content/courses/program-security/security-intro.md
> +discussed.
```suggestion
Even though each security
vulnerability may seem "simple," there's a lot to discuss. These lessons contain less prose and more code, ensuring you gain a solid understanding of the security risks
discussed.
```

Nothing to do with you but this was a bit sales-y.

2024-09-05 05:46 UTC, 0xCipherCoder commented on content/courses/program-security/security-intro.md
> +in those lessons should help you avoid some common Solana exploits on your own.
Sure, got it.

2024-09-05 11:42 UTC, 0xCipherCoder commented on content/courses/program-security/security-intro.md
> +in those lessons should help you avoid some common Solana exploits on your own.
This is added as per comment.

2024-09-05 11:43 UTC, 0xCipherCoder commented on content/courses/program-security/security-intro.md
> +If you completed the Basic Security lesson, the first few topics in this module
Fixed all the links and made small change in a complete sentence.

2024-09-05 11:43 UTC, 0xCipherCoder commented on content/courses/program-security/security-intro.md
> +you’ll encounter new types of attacks. We encourage you to explore all of them.
This suggestion on of above comment.

2024-09-05 11:53 UTC, 0xCipherCoder commented on content/courses/program-security/security-intro.md
> +explore topics in the order that suits you best.
Added as `info` default callout.

2024-09-05 12:04 UTC, 0xCipherCoder commented
> A few changes, but mainly to old code, and I've added suggestions. Good work, fix the comments below and we can get this in quickly. There are two other entries for this lesson but this the most comprehensive, so you have a good chance to win.

Thanks! @mikemaccana I have added all the requested changes and suggestions. Please take a look and let me know if there is any additional feedback.

2024-09-11 02:27 UTC, merged

2024-09-11 02:27 UTC, mikemaccana commented
Another winning PR. Thanks @0xCipherCoder !

2024-09-11 03:49 UTC, 0xCipherCoder commented
> Another winning PR. Thanks @0xCipherCoder !

Thanks! @mikemaccana