Native onchain development - Updated program state management lesson
solana-foundation/developer-content pull request #413
Opened 2024-09-03 02:46 UTC by 0xCipherCoder

…style

### Problem

### Summary of Changes
- Updated content as per given guidelines.
- Updated styling and grammar fixes
- Updated code snippets with latest Rust and solana program 
- Updated program code and updated link 

Fixes #
Updated program code - https://beta.solpg.io/66d67458cffcf4b13384d331

2024-09-05 02:27 UTC, mikemaccana requested changes
A few changes are required, see the comments above, but this looks good. 👍 Note multiple people are competing for this lessons s competition is hot!

2024-09-05 02:27 UTC, mikemaccana commented on content/courses/native-onchain-development/program-state-management.md
> +- A Cross Program Invocation (CPI) to the `create_account` instruction on the
instruction handler. See https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#prose

```suggestion
- A Cross Program Invocation (CPI) to the `create_account` instruction handler on the
```

2024-09-05 02:27 UTC, mikemaccana commented on content/courses/native-onchain-development/program-state-management.md
> +stateless. Instead of storing state on the program, programs use Solana's
```suggestion
stateless. Instead of storing state alongside the program's executable, programs use Solana's
```

2024-09-05 14:56 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +  seeds, and it is used as the address for a storage account.
Improved this as per suggestions.

2024-09-05 14:59 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +instructions in the [first part of this lesson](basic-program-pt-1).
Fixed link as per guidelines to point to the enum section.

2024-09-05 15:01 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +account is set to true if the derived PDA matches any of the passed accounts.
Added more details for clarity with explicit callouts.

2024-09-05 15:03 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +mutable reference to `accounts`.
Have made it better for readability and clarity with detailed explaination.

2024-09-05 15:04 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +In the last lesson, we deserialized the instruction data passed in by the user
Updated as per guidelines to the previous lesson.

2024-09-05 15:08 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/program-state-management.md
> +serializing account data.
Updated for better readability and clarity. Let me know if it needs further improvement.

2024-09-05 15:09 UTC, 0xCipherCoder commented
> A few changes are required, see the comments above, but this looks good. 👍 Note multiple people are competing for this lessons s competition is hot!

Thanks! @mikemaccana I have updated the content and resolved all the comments. Please review and let me know if there is any additional feedback.

2024-09-11 02:48 UTC, merged

2024-09-11 02:48 UTC, mikemaccana commented
More excellent work and another winner. 🏆

2024-09-11 03:48 UTC, 0xCipherCoder commented
> More excellent work and another winner. 🏆

Thanks! @mikemaccana