Rust Procedural Macros Lesson
solana-foundation/developer-content pull request #435
Opened 2024-09-06 11:41 UTC by Ayushjhax

### Problem
The original lesson on Rust Procedural Macros lacked depth in certain areas and needed updates to reflect current best practices.

### Summary of Changes

1. Expanded Rust concepts section with more detailed explanations
2. Added new subsections on `syn` and `quote` crates
3. Updated and expanded code examples throughout
4. Refined procedural macro example with step-by-step explanations
5.Enhanced Anchor procedural macros section

2024-09-12 11:36 UTC, Ayushjhax commented
Is a review possible, sir, before the deadline? @mikemaccana

2024-09-12 21:55 UTC, mikemaccana requested changes
I'm going to get one of my colleagues with more Rust experience to review this - @ASCorreia can you please check this out?

2024-09-12 21:55 UTC, mikemaccana commented on content/courses/program-optimization/rust-macros.md
> +anchor-lang = "0.29.0"
Use 0.30.1 per CONTRIBUTING.md

2024-09-12 21:57 UTC, mikemaccana requested changes
See comments above.

2024-09-12 22:03 UTC, Ayushjhax commented on content/courses/program-optimization/rust-macros.md
> +anchor-lang = "0.29.0"
Thank you; I fixed it

2024-09-22 13:23 UTC, Ayushjhax commented
@ASCorreia sir if possible can you review this?

2024-09-25 12:41 UTC, ASCorreia reviewed
In general, a pretty good improvement from the previous state.

Some minor changes and a small rework might be needed, as stated in the review comments.

2024-09-25 12:41 UTC, ASCorreia commented on content/courses/program-optimization/rust-macros.md
> +use syn::{parse_macro_input, DeriveInput, Data, Fields};
`syn::Data` and `syn::Fields` is being imported, but the import is not being properly used in the `describe_struct` associated function

2024-09-25 12:41 UTC, ASCorreia commented on content/courses/program-optimization/rust-macros.md
> +pub fn describe_struct(input: TokenStream) -> TokenStream {
This method needs rework in order to be inline with your previous changes (import usage, usage of quote! inside format!, etc). Looks like you forgot to update this section according to your previous changes

Also, text is saying that a describe() method will be implemented, and you're implementing a describe_struct() method. Please revise methods naming

2024-09-25 12:41 UTC, ASCorreia commented on content/courses/program-optimization/rust-macros.md
> +    eprintln!("{:#?}", ast);
Since syn is already being imported in the use section, LitStr can be imported directly in order to create a cleaner use section

2024-09-25 20:35 UTC, Ayushjhax commented
Thanks for the feedback! Let me know if further changes are needed! @ASCorreia @mikemaccana

2024-09-30 12:36 UTC, Ayushjhax commented
@mikemaccana Sir, I have resolved all the requests mentioned

2024-12-11 00:17 UTC, closed without merging