Program security - Bump seed canonicalization lesson updated
solana-foundation/developer-content pull request #446
Opened 2024-09-08 04:44 UTC by 0xCipherCoder

### Problem

### Summary of Changes

- Updated code snippets with the latest anchor version
- Fixed content,
- Fixed grammar and styling
- Fixed as per guidelines

Fixes #
Unboxed PRs
Starter - https://github.com/Unboxed-Software/solana-bump-seed-canonicalization/pull/2
Solution - https://github.com/Unboxed-Software/solana-bump-seed-canonicalization/pull/3

2024-09-13 10:56 UTC, 0xCipherCoder commented
@mikemaccana Please review this once. Let me know if any suggestions.

2024-09-30 07:10 UTC, mikemaccana requested changes
Just some mild fixes but should be good to go straight after.

2024-09-30 07:59 UTC, 0xCipherCoder commented on content/courses/program-security/bump-seed-canonicalization.md
> +    data: Account<'info, Data>,
Formatted as per rustfmt with deleteme.rs.

2024-09-30 08:00 UTC, 0xCipherCoder commented on content/courses/program-security/bump-seed-canonicalization.md
> +    let numClaims = 0;
Updated with full words.

2024-09-30 08:01 UTC, 0xCipherCoder commented on content/courses/program-security/bump-seed-canonicalization.md
> +      1 * LAMPORTS_PER_SOL,
Updated to check if the minimum is less than or equal to 0.5 SOL to request for 1 SOL.

2024-09-30 08:02 UTC, 0xCipherCoder commented on content/courses/program-security/bump-seed-canonicalization.md
> +[`solution` branch of the same repository](https://github.com/Unboxed-Software/solana-bump-seed-canonicalization/tree/solution).
Updated repo urls for starter and solution branch.

2024-10-01 01:28 UTC, merged