Program security - PDA sharing lesson updated
solana-foundation/developer-content pull request #449
Opened 2024-09-08 17:05 UTC by 0xCipherCoder

### Problem

### Summary of Changes

- Updated code snippets with the latest anchor version
- Fixed content with updated version changes
- Fixed grammar and styling
- Fixed as per guidelines

Fixes #

Unboxed PRs
Starter - https://github.com/solana-developers/pda-sharing/pull/1
Solution - https://github.com/solana-developers/pda-sharing/pull/2

2024-09-10 22:05 UTC, mikemaccana requested changes
Great work, some minor changes but not many, we should be able to get this in immediately once done.

2024-09-10 22:05 UTC, mikemaccana commented on content/courses/program-security/pda-sharing.md
> +    await spl.mintTo(
Just import `mintTo`, to match the other lessons.

2024-09-10 22:05 UTC, mikemaccana commented on content/courses/program-security/pda-sharing.md
> +    await spl.mintTo(
PS nice work getting rid of the unnecessary delay in the old code.

2024-09-10 23:31 UTC, 0xCipherCoder commented on content/courses/program-security/pda-sharing.md
> +        )
Removed impl and created separate methods get_transfer_ctx and get_secure_transfer_ctx. Fixed and pushed this changes in unbox PRs.

2024-09-10 23:32 UTC, 0xCipherCoder commented on content/courses/program-security/pda-sharing.md
> +    await spl.mintTo(
Imported required functions only and updated Unbox PRs as well for the same.

2024-09-10 23:36 UTC, 0xCipherCoder commented
> Great work, some minor changes but not many, we should be able to get this in immediately once done.

Thanks! @mikemaccana I have updated code as per comment and respective Unbox PRs in both starter and solution branch.

2024-09-11 02:30 UTC, merged

2024-09-11 02:31 UTC, mikemaccana commented
Thanks @0xCipherCoder . You've won this one too.

2024-09-11 03:45 UTC, 0xCipherCoder commented
Thanks! @mikemaccana