Added overview to intro-to-anchor chapter
solana-foundation/developer-content pull request #466
Opened 2024-09-11 10:53 UTC by shivaji43

### Problem
Added overview to intro-to-anchor chapter and given a brief.

### Summary of Changes
Gave a brief intro to Anchor and it applications and how it is used.

Fixes #

2024-09-11 12:25 UTC, shivaji43 commented
@nickfrosty  Can you please check the PR  asap , the submission date is very close

2024-09-24 09:37 UTC, mikemaccana requested changes
This PR needs significant changes to be merged. Please see the comments above and provide an update if you're still interested in working on this.

2024-09-24 09:37 UTC, mikemaccana commented on content/courses/onchain-development/intro-to-anchor.md
> +  function, simplifying the process of executing program logic.
These should be indented below their parent.

2024-09-24 09:37 UTC, mikemaccana commented on content/courses/onchain-development/intro-to-anchor.md
> +Anchor project and is stored in the target/deploy directory.
'Programs are deployed at addresses' needs a full stop.

'In the same way, Solana programs can be deployed using their program ID,' - in the same way as what? I thought the previous sentence referred to Solana programs.

'and Anchor programs can also be deployed with a unique public key' - Anchor programs are also Solana programs.

2024-09-24 09:37 UTC, mikemaccana commented on content/courses/onchain-development/intro-to-anchor.md
> +- `Instructions`: These are the actions users and programs can trigger. Anchor
No. See [CONTRIBUTING.md. ](https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#prose) re instructions.

2024-09-24 10:44 UTC, shivaji43 commented
I am still interested to work on this and will try to make the changes according to the comments.

2024-10-13 06:31 UTC, closed without merging