Generalized state compression
solana-foundation/developer-content pull request #470
Opened 2024-09-11 16:27 UTC by danielAsaboro

### Problem

The documentation initially contained complex language and passive voice, making it difficult for beginners to understand. However, the code was functioning correctly once the dependencies were updated to their latest versions.

### Summary of Changes

- **Improved Clarity**: Revised the text to enhance readability and clarity for beginners. Removed passive voice and simplified explanations.
- **Updated Code Samples**: Adjusted the code examples to be compatible with the latest versions of dependencies.
- **Fixes**: Addressed any identified issues related to clarity and code compatibility.

2024-09-19 12:23 UTC, danielAsaboro commented
Zero update on this?
I think it's also worth noting that's it's for the Update Solana Developer Lessons

2024-09-24 05:43 UTC, mikemaccana commented
@danielAsaboro we had a live course in NY with 24 people learning new material, then Rustconf then Breakpoint! Reviewing this now.

2024-09-24 07:18 UTC, mikemaccana requested changes
A good start, there's a few things to fix but you should be able to get through them easily by following the comments above.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> +to this instruction.
```suggestion
The initialization instruction will create a CPI (Cross-Program Invocation) to
call the `init_empty_merkle_tree` instruction from the State Compression
Program. You’ll need to provide the maximum depth and buffer size as arguments
to this instruction.
```

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> + );
Fix indentation above.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> +transaction logs.
```suggestion
Additionally, the State Compression Program works in conjunction with a separate
"Noop" program. A [no-op program](https://en.wikipedia.org/wiki/NOP_(code)) does nothing - literally 'no operation.' The Solana Noop Program only logs data to the ledger state, however that logging is essential to state compression:

When you store compressed data, it’s passed to the State Compression Program, which hashes the data and emits it as an "event" to the Noop Program. While the hash is stored in the concurrent Merkle tree, the raw data can still be accessed via the Noop Program’s
transaction logs.
```

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> +transaction logs.
Most readers won't know what a no-op program is.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> + }
fix indentation in all these code sections, below too.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> +adding the following dependency:
```suggestion
Next, we'll add the `spl-account-compression` crate with the `cpi `feature enabled.
To do this, update the `Cargo.toml` file located at `programs/compressed-notes` by
adding the following dependency:
```

Use code blocks for all file names, config options, package names, etc.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> + wrap_application_data_v1,
reminder to fix all indents

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
> +In our setup, all instructions will use the same accounts, so we'll create a
```suggestion
In our setup, all instructions handlers will use the same accounts, so we'll create a
```

Please always refer to the functions that handle instructions as instruction handlers. **Fix this everywhere**. See CONTRIBUTING.md.

2024-09-24 07:18 UTC, mikemaccana commented on content/courses/state-compression/generalized-state-compression.md
>  it("Add Max Size Note", async () => {
Fix all the test names. See CONTRIBUTING.md

2024-09-25 11:56 UTC, danielAsaboro commented
> @danielAsaboro we had a live course in NY with 24 people learning new material, then Rustconf then Breakpoint! Reviewing this now.

Oh, that's great to hear. I trust it was all great;
I was just afraid we were being ignored; glad to know I was wrong

2024-09-25 12:29 UTC, danielAsaboro commented on content/courses/state-compression/generalized-state-compression.md
> +   Merkle tree.
Thank you very much, Mike;
I love your editing style, hope to work more with you

2024-09-26 10:32 UTC, danielAsaboro commented
Hi Mike, i've implemented the changes you suggested,
and also made the test section more explanatory as a lot of people (including myself) get confused easily with it
Could you please take another look at it so i know if there are edits to be made -- thank you

2024-09-30 07:42 UTC, mikemaccana commented
@danielAsaboro can you also please fix the recent conflicts? Thanks!

2024-09-30 14:06 UTC, danielAsaboro commented
> @danielAsaboro I'm going to do a final review of this now, but can you also please fix the recent conflicts? Thanks!
> 
> please also remove changes to the package.lock and other unrelated files.

Hi Mike, it's great to hear from you again.

To be clear, when you say 'remove changes to the package.lock and other unrelated files', do you mean i should revert the PR i made to unbox?

2024-10-01 09:16 UTC, mikemaccana requested changes
Great! Lots of small things but they're pretty easy. Give me a buzz once done and we'll get this in!

> To be clear, when you say 'remove changes to the package.lock and other unrelated files', do you mean i should revert the PR i made to unbox?

No, this I mean you shoudl remove the two files that aren't `.md` files in this PR 

Your code is now in https://github.com/solana-developers/anchor-compressed-notes. Note that I think you're just using 'main' rather than 'solution' for your changes. We can get rid of the 'solution' branch if you're not using it (as long as the URL in this lesson is correct).

BTW @danielAsaboro I'm on telegram and twitter as `mikemaccana` if you want to communicate faster.

2024-10-02 14:58 UTC, danielAsaboro commented on content/courses/state-compression/generalized-state-compression.md
> +#### 4. Create `create_note_tree` Instruction
Nice call there, Mike

2024-10-02 15:04 UTC, danielAsaboro commented on content/courses/state-compression/generalized-state-compression.md
> +    /// The payer for the transaction, who also owns the note.
Oh, I write code primarily in Dart and three forward slashes is how we document this kind of content

2024-10-02 15:38 UTC, danielAsaboro commented on content/courses/state-compression/generalized-state-compression.md
>      provider.connection.rpcEndpoint,
yes, they are designed to work local development environments..
please correct me if i'm are wrong

2024-10-02 22:33 UTC, danielAsaboro commented
hmmm, this one took my tiime...I had an issue with checks when i remove my package json and yarn lock out;

perhaps, anyone could help fix

2024-10-02 22:38 UTC, danielAsaboro commented
> Great! Lots of small things but they're pretty easy. Give me a buzz once done and we'll get this in!
> 
> > To be clear, when you say 'remove changes to the package.lock and other unrelated files', do you mean i should revert the PR i made to unbox?
> 
> No, this I mean you shoudl remove the two files that aren't `.md` files in this PR
> 
> Your code is now in https://github.com/solana-developers/anchor-compressed-notes. Note that I think you're just using 'main' rather than 'solution' for your changes. We can get rid of the 'solution' branch if you're not using it (as long as the URL in this lesson is correct).
> 
> BTW @danielAsaboro I'm on telegram and twitter as `mikemaccana` if you want to communicate faster.

Hi Mike, I already reached out to you through Twitter 💙

2024-10-04 07:17 UTC, merged