Update Lookup Tables (LUTs) course
solana-foundation/developer-content pull request #476
Opened 2024-09-12 11:54 UTC by darkvallen

### Summary of Changes
Update the Address Lookup Tables (LUTs) course to comply with the SoLana contributing guide.

- Simplified explanations of versioned transactions and Address Lookup Tables (LUTs).
- Updated code examples to align with best practices.
- Ensured the documentation followed the guidelines from the Solana contributing guide.
- Enhance readability

2024-09-24 09:12 UTC, mikemaccana requested changes
A good start but a few things to fix, see comments above and we can get this merged - make sure you pay attention to CONTRIBUTING.md

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +Note that After you create or extend a lookup table, it must "warm up" for one
```suggestion
Note that after you create or extend a lookup table, it must "warm up" for one
```

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +});
We don't need IIFEs or main wrappers. See https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#jsts

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +To run the example, execute `npm start`. This process will:
Just use esrun.

```
npx esrun try-large-transaction.ts
```

See https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#jsts

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
>  import * as web3 from "@solana/web3.js";
Just import the things from web3 you will actually use, this helps tree-shaking and will fit in with more of the other  code.

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +To begin, download the starter code from the "starter" branch of this
You can probably do without this repo. `initializeKeypair` is in `helpers`. Just ask people to make a file. See 'don't make custom helper functions' in https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#jsts

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +To run the example, execute `npm start`. This process will:
Do the same - get people to make `do-something.ts`, edit the file (no IIFE/main wrappers)  and then `npx esrun do-something.ts` - for all other code.

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +    const checkInterval = 1000; // Interval to check for new blocks (1000ms)
```
const SECOND=1000;
```

then later:

```
const checkInterval = 1 * SECOND;
````

2024-09-24 09:12 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +  const slot = await getSlot(connection);
Where is getSlot in https://github.com/solana-developers/helpers?

2024-09-24 09:25 UTC, mikemaccana commented
@darkvallen multiple people have submitted for this but I want to let you know you can easily win this one - you're much closer to having an accepted PR. Just get it in quick!

2024-09-24 13:40 UTC, darkvallen commented
> @darkvallen multiple people have submitted for this but I want to let you know you can easily win this one - you're much closer to having an accepted PR. Just get it in quick!

Updated @mikemaccana , let me know if there's any further adjustment

2024-10-02 08:26 UTC, mikemaccana commented
Thanks @darkvallen ! You won this one.

2024-10-02 08:28 UTC, merged