Fixed Lookup Table Course and Lab
solana-foundation/developer-content pull request #479
Opened 2024-09-12 16:53 UTC by devvspaces

### Problem

The `Versioned Transactions and Lookup Tables` course has some grammatical errors also in the Lab and I found some deprecated code and incorrect code snippets.

### Summary of Changes

Typos, grammatical errors, code snippets and repos, eliminated async wrappers

### Fixes

- Added keywords for SEO metadata
- Use <Callout> for notes, tips, warnings, and cautions
- Avoided picking favorites by linking to [solana.com/rpc](https://solana.com/rpc) instead of listing specific names
- Added prerequisite installations where necessary
- Fixed Unboxed Lesson and Solution
- Fixed Typo
- Fixed grammatical errors using Grammarly and Hemmingway

2024-09-24 09:28 UTC, mikemaccana requested changes
I've left some comments about for the first few parts of this PR, please read them, make changes and then re-submit if you want to get this merged and win this lesson bounty.

2024-09-24 09:28 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +  "Harness a great deal of accounts through the application of lookup tables."
Honestly the old one was simpler. Plain language is important. 

1. Not everyone speaks english. Not everyone knows the word 'harness'. 
2. People want simple clear directions. It should be clear that if they need a lot of accounts in their translations, they should use lookup tables.

> "Use large amounts of accounts in a transaction by using lookup tables."

2024-09-24 09:28 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +  tool called Address Lookup Tables (LUTs).
> **Versioned Transactions** are like different versions of a recipe that allow
  us to use both old and new ingredients. 
  
 Is too complex. Wedon't need a cooking analogy. People understand versions. The only thing we need to convey is that if they want to use lots of accounts, they need a V0 transaction not a legacy transaction.

2024-09-24 09:28 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +You can get a RPC providers from [Solana RPC](https://solana.com/rpc).
We shouldn't advertise one particular RPC provider. This is mentioned in CONTRIBUTING.md

2024-09-24 09:28 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
>  import * as web3 from "@solana/web3.js";
Just import the bits of web3 you need.

2024-09-24 09:28 UTC, mikemaccana commented on content/courses/program-optimization/lookup-tables.md
> +- `createLookupTable` - creates a new LUT's account
No. The LUT doesn't possess the account, the LUT *is* the account.

2024-09-24 10:38 UTC, devvspaces reviewed
I have fixed the issues and made appropriate updates to my PR on Unboxed

2024-09-24 10:42 UTC, devvspaces reviewed
Resolved them all thanks @mikemaccana

2024-09-27 12:19 UTC, devvspaces commented
hi @mikemaccana i am done with the changes requested here

2024-10-07 03:25 UTC, mikemaccana commented
Thanks @devvspaces  ! While you didn't win this particular lesson, there's a lot of good stuff in this PR we'd still love to have your updates. Could you please rebase on top of current main?

2024-10-07 03:26 UTC, mikemaccana requested changes
See comment abovere: rebasing!

2024-10-14 22:02 UTC, devvspaces commented
@mikemaccana i will do that thanks

2024-10-15 18:43 UTC, devvspaces commented
Done that @mikemaccana

2024-12-10 00:17 UTC, closed without merging