Tokens and Nfts - Updated token-program-advanced lesson
solana-foundation/developer-content pull request #488
Opened 2024-09-16 15:21 UTC by ubadineke

### Problem

### Summary of Changes
- Updated solana's client from web3 to web3.js
- Added top level async function
- Added example explorer transaction link for all lab exercises.
- Separated lab exercises(revoke and burn) into different files.

Fixes #

2024-09-17 00:04 UTC, mikemaccana requested changes
See comments above.

2024-09-17 00:04 UTC, mikemaccana commented on content/courses/tokens-and-nfts/token-program-advanced.md
> +(async () => {
You don't need to add this, in fact you were instructed to remove it: https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#jsts

Also add `filesname=` to the code snippets. See https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#file-names

2024-09-17 06:48 UTC, ubadineke commented
@mikemaccana I've implemented the changes.
check it out.

2024-09-24 17:29 UTC, ubadineke commented
Hi @mikemaccana 
Are there any other changes you want me to implement.

2024-11-19 19:35 UTC, mikemaccana approved these changes

2024-11-19 19:35 UTC, mikemaccana commented
@nickfrosty this looks good, can you please merge it?

2024-12-25 00:15 UTC, closed without merging