updated token-program.md course
solana-foundation/developer-content pull request #492
Opened 2024-09-19 19:38 UTC by Ozodimgba

### Problem
Some of the methods used in the `@solana/spl-token` package in this course have been updated and might cause confusion for learners interacting with the package presently

### Summary of Changes

- `createMint` now uses `createInitializeMint2Instruction`,
- `createAssociatedTokenAccount` method replaced asynchronous `getAssociatedTokenAddress` calls with synchronous `getAssociatedTokenAddressSync` to make sure token account is only created when none exists
- `allowOwnerOffCurve` parameter is a necessary parameter for certain use case like vaults and interactions with multi sig wallets. [see the @solana/spl-token commit here](https://github.com/solana-labs/solana-program-library/commit/5cd54795fa8364037431dcca561f24b0ed2baaab)

2024-10-17 20:27 UTC, mikemaccana commented on content/courses/tokens-and-nfts/token-program.md
> +  accounts for PDAs, necessary for vaults and multi-sig wallets.
```suggestion
- `allowOwnerOffCurve` - defaults to false, used to create token
  accounts for PDAs, necessary for vaults and multi-sig wallets.
```

2024-10-17 20:32 UTC, mikemaccana commented
Thanks! Can you also please update this lesson to import the specific functions used from web3.js and spl-token, rather than using `import * as token`? This will match the other lessons.

2024-10-17 20:32 UTC, mikemaccana requested changes
Thanks! Can you also please update this lesson to import the specific functions used from web3.js and spl-token, rather than using `import * as token`? This will match the other lessons.

2024-10-18 12:13 UTC, Ozodimgba commented
Fixed up chief. Updated this course for the Superteam bounty but review is coming after. Am I still eligible?

2024-12-10 00:17 UTC, closed without merging