Native onchain development - Updated cross program invocation lesson
solana-foundation/developer-content pull request #493
Opened 2024-09-20 13:43 UTC by 0xCipherCoder

### Problem

### Summary of Changes

- Updated content as per given guidelines.
- Updated styling and grammar fixes
- Updated code snippets with latest Rust and solana program
- Updated program code and updated links

Fixes #

Unboxed PRs
Movie program solution add comments as a starter - https://github.com/Unboxed-Software/solana-movie-program/pull/9
Movie program solution add tokens - https://github.com/Unboxed-Software/solana-movie-program/pull/10
Movie token client - https://github.com/Unboxed-Software/solana-movie-token-client/pull/1

2024-10-02 07:15 UTC, mikemaccana requested changes
More great work, a few small fixes but all very simple.

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +the previous PDA lesson. If you just completed that lesson, you're all set and
```suggestion
the [previous PDA lesson](ADD LINK HERE). If you just completed that lesson, you're all set and
```

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +[starter code from the `solution-add-comments` branch](https://github.com/Unboxed-Software/solana-movie-program/tree/solution-add-comments).
use https://github.com/solana-developers/movie-program/tree/solution-add-comments - check it has your updates

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +```toml
good spot 👍

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +[last lesson program derived addresses](/content/courses/native-onchain-development/program-derived-addresses.md),
```suggestion
[program derived addresses lesson](/content/courses/native-onchain-development/program-derived-addresses.md),
```

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +```
Nice addition. In future we might have a 'deploying troubleshooting' resource we can link to but we can leave this here for now.

2024-10-02 07:15 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
>  you're calling will read or write.
```suggestion
added to the instruction, you must include all the accounts that the program
you're invoking will read or write.
```

2024-10-02 08:23 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +then make sure to tailor the script accordingly.
@mikemaccana Can you please clarify if my understanding is correct? We should be deleting the content of the repo and just keep the `index.ts` content in a file name `initialize-review-token-mint.ts`.  Then repo will have only one script without any `package.json` or other dependencies that are required for the script? Bit confused here.

2024-10-02 15:47 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +  instruction in a program can be invoked by another program via a CPI.
Updated as per suggestion.

2024-10-02 15:47 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
>      signers_seeds: &[&[&[u8]]]
Updated as per suggestion.

2024-10-02 15:48 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +retains that status in the invoked program.
Yes this sounds good and updated it everywhere as per suggestion.

2024-10-02 15:48 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
>  [@solana/spl-token](https://solana-labs.github.io/solana-program-library/token/js/)).
Yes, updated as per suggestion.

2024-10-02 15:50 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
>  [features of the `vec` macro available to you here](https://doc.rust-lang.org/alloc/vec/struct.Vec.html#).
Updated as per suggestion.

2024-10-02 15:51 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +the previous PDA lesson. If you just completed that lesson, you're all set and
Updated as per suggestion.

2024-10-02 15:53 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
>  you're calling will read or write.
Updated as per suggestion.

2024-10-02 15:54 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +- `data` - A byte buffer representing the data passed to the callee program as a
Updated as per suggestion everywhere.

2024-10-03 03:35 UTC, mikemaccana commented on content/courses/native-onchain-development/cross-program-invocations.md
> +then make sure to tailor the script accordingly.
No. Please add some markdown content like.

```
Before you can start testing whether or not adding a review or comment sends you
tokens, you need to initialize the program's token mint. 

```typeescript filename=initialize-review-token-mint.ts
console.log('some actual code')
```

Then run the file with `npx esrun initialize-review-token-mint.ts`. Your token mint will now be created.
````

2024-10-03 04:46 UTC, 0xCipherCoder commented on content/courses/native-onchain-development/cross-program-invocations.md
> +then make sure to tailor the script accordingly.
I've updated the content to run it with esrun according to your suggestions.

2024-10-04 04:24 UTC, merged