feat: update course to use umi and bubblegum plugin
solana-foundation/developer-content pull request #510
Opened 2024-09-25 10:53 UTC by jim4067

### Problem

### Summary of Changes
update compressed nfts lesson to use umi and mpl-bubblegum package

Fixes #

2024-09-30 04:02 UTC, mikemaccana requested changes
Great work! Lots of small changes (and a few TODOs) but you're 90% of the way there and will likely win this one.

2024-10-02 09:53 UTC, jim4067 commented on content/courses/state-compression/compressed-nfts.md
> +umi.use(keypairIdentity(umiKeypair)).use(mplBubblegum()).use(dasApi());
prettier formats this to one line in the md

2024-10-02 17:18 UTC, jim4067 commented on content/courses/state-compression/compressed-nfts.md
> +<!-- todo(should there be a section for creating a collection with MPL metadata) -->
I linked the section for creating a collection NFT in the nfts-with-metaplex lesson

2024-10-02 17:43 UTC, jim4067 commented on content/courses/state-compression/compressed-nfts.md
> +[solution code](<!-- todo(Jimii) -->) is available.
Here is the demo repo -> https://github.com/jim4067/cnft-demo

2024-10-02 17:43 UTC, jim4067 commented on content/courses/state-compression/compressed-nfts.md
> -}
sounds awesome. Let me look a little bit more into it

2024-10-03 02:19 UTC, mikemaccana commented on content/courses/state-compression/compressed-nfts.md
>  [solution code](<!-- todo(Jimii) -->) is available.
```suggestion
[solution code](https://github.com/solana-foundation/compressed-nfts) is available.
```

2024-10-03 02:19 UTC, mikemaccana approved these changes

2024-10-03 02:19 UTC, merged