Update compressed nfts
solana-foundation/developer-content pull request #523
Opened 2024-09-26 18:34 UTC by adpthegreat

- Followed guidelines in contributing.md
- Refactored it to use newest dependencies 
- Replaced @metaplex- foundation/js with @metaplex-foundation-umi
- Replaced old methods with their corresponding umi methods 
- Replaced all old code snippets 
- Gave clearer variable names
- Removed redundant code 
- Ran prettier 

updated lesson code and created Unboxed PRs

[solution code](https://github.com/Unboxed-Software/solana-cnft-demo/pull/2)
[starter code](https://github.com/Unboxed-Software/solana-cnft-demo/pull/3)

2024-10-02 10:57 UTC, adpthegreat commented
Ran prettier locally multiple times but it still fails in CI and I don't know the reason

2024-10-13 07:53 UTC, mikemaccana requested changes
I haven't reviewed this fully, but it looks good so far - to speed up the review, can you please remove the smart quotes (just use `'`) and remove the other files from this PR? This will reduce the 'noise' and I'll then check out the remaining changes.

2024-10-13 07:53 UTC, mikemaccana commented on content/courses/state-compression/compressed-nfts.md
> +  - Create a compressed NFT collection using Metaplex’s Bubblegum program
No need for smart quotes. Just use `'`

2024-10-13 07:53 UTC, mikemaccana commented on content/courses/state-compression/compressed-nfts.md
> +[**State Compression**](https://solana.com/docs/advanced/state-compression) to
Nice word adding the link for the term.

2024-10-13 07:53 UTC, mikemaccana commented on content/courses/state-compression/compressed-nfts.md
> +4. Hash pairs of leaves together, to create “branches”
Good work, this is much clearer than the older content.

2024-10-13 07:53 UTC, mikemaccana commented on content/courses/state-compression/compressed-nfts.md
> +   leaf has not changed
Also much clearer.

2024-10-13 11:33 UTC, adpthegreat commented
Alright I'll do that , the other files from the PR included was because I was trying to fix the prettier CI issues, I'll probably just have to remove the last three or four commits

2024-12-06 19:13 UTC, closed without merging