fix: Add rating validation to update_movie_review function
solana-foundation/developer-content pull request #541
Opened 2024-09-27 12:08 UTC by TanmayDhobale

### Problem

The `update_movie_review` function did not include any check on the rating input, allowing ratings to be set outside the valid range of 1-5.

### Summary of Changes

- Added a `require!` macro in the `update_movie_review` function to validate the rating
- Ensures that the rating is always between 1 and 5, inclusive
- Throws a `MovieReviewError::InvalidRating` error if an invalid rating is provided

This change prevents invalid data from being stored in movie review accounts and maintains consistency with the `add_movie_review` function's validation.

Fixes  #431

2024-09-30 04:52 UTC, mikemaccana commented
Thanks for spotting this! Can you please rebase this on current `main`? That will remove all the unrelated fixes.

2024-09-30 07:22 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +// We require that the rating is between 1 and 5
```suggestion
    // We require that the rating is between 1 and 5
```

2024-09-30 07:32 UTC, mikemaccana requested changes
Lots of small fixes but should be good to go once they're fixed.

2024-09-30 07:32 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +function)
Fix this junk

2024-09-30 07:32 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +2. An object specifying either the `mint` or the `programId`
```suggestion
2. Either the `mint` or the `programId`
```

2024-09-30 07:32 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +  <Field name="dataSlice" type="object" optional={true}>
Fix indentation.

2024-09-30 07:32 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +> Note: The second parameter must include either `mint` or `programId`. You
```suggestion
> Note: The second parameter must be either `mint` or `programId`. You
```

2024-09-30 07:32 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +
Use a Callout box for this. See CONTRIBUTING.md

2024-09-30 07:32 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +    // We require that the rating is between 1 and 5
Honestly these comments can just be deleted. Comments should be for the 'why' - anyone who reads this code will know what it does.

2024-09-30 07:32 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +[solution code](https://github.com/Unboxed-Software/anchor-movie-review-program/tree/solution-pdas)
use https://github.com/solana-developers/anchor-movie-review-program instead of this repo, everywhere.

2024-09-30 07:32 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +[solution code](https://github.com/Unboxed-Software/anchor-student-intro-program).
fix this link too

2024-09-30 07:32 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +ix: Add rating validation to update_movie_review function)
is this left over? it doesn't make much sense.

2024-10-01 04:58 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +2. An object specifying either the `mint` or the `programId`
Please don't close discussions i you don't want to implement them. Instead say why you don't like the suggestion.

2024-10-01 04:59 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +...
```suggestion
    ...
```

2024-10-01 05:00 UTC, mikemaccana commented on content/courses/onchain-development/anchor-pdas.md
> +...
```suggestion
    ...
```

2024-10-01 05:02 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +> Note: The second parameter must include either `mint` or `programId`. You
@TanmayDhobale Please don't close discussions i you don't want to implement them. Instead say why you don't like the suggestion.

2024-10-01 05:02 UTC, mikemaccana requested changes
This is good PR, but you need to fix the issues in the discussion and remove changes to yarn.lock

2024-10-01 05:41 UTC, TanmayDhobale commented
> This is good PR, and we can merge it, but you first need to:
> 
>     1. fix the issues in the discussion
> 
>     2. remove all changes to yarn.lock
> 
>     3. fix the conflicts

can u check

2024-10-02 01:50 UTC, mikemaccana requested changes
Still a few small things to fix.

2024-10-02 01:50 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +
This is duplicated. 

Also please change it to 'as a base58 encoded'

2024-10-02 01:50 UTC, mikemaccana commented on docs/rpc/http/getTokenAccountsByOwner.mdx
> +        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
This copies the line above.

2024-10-02 01:50 UTC, mikemaccana commented on yarn.lock
> +"@effect-ts/core@^0.60.2", "@effect-ts/core@^0.60.5":
You do not need to change this file. Remove it from the PR.

2024-10-03 06:53 UTC, TanmayDhobale commented
@mikemaccana

2024-11-26 23:00 UTC, closed without merging