Feat: Getting Started with Solang Guide
solana-foundation/developer-content pull request #6
Opened 2023-07-17 15:39 UTC by ZYJLiu

2023-07-17 20:27 UTC, nickfrosty requested changes

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +   [Anchor Framework](https://www.anchor-lang.com/docs/installation). Anchor a
```suggestion
   [Anchor Framework](https://www.anchor-lang.com/docs/installation). Anchor is a
```

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +   widely used framework in the Solana ecosystem used to simplify the process of
```suggestion
   widely used framework in the Solana ecosystem and simplifies the process of
```

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +your project's `./solidity` directory, you’ll find the following contract below:
```suggestion
your project's `./solidity` directory, you’ll find the following contract below, which includes:
```

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +The contract includes:
```suggestion

```

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +
```suggestion
### Important Differences

```

2023-07-17 20:27 UTC, nickfrosty commented on developers/guides/solang/getting-started.md
> +Here's an important distinction between EVM smart contracts and Solana programs:
```suggestion
### Storing of state data

An important distinction between EVM smart contracts and Solana programs is how each stores "state" variables/data:
```

2023-07-17 20:27 UTC, nickfrosty commented
Content looks good, just some minor nits

2023-07-17 20:40 UTC, ZYJLiu reviewed
Thanks nick!

2023-07-18 13:10 UTC, nickfrosty approved these changes

2023-07-18 13:10 UTC, merged