edited setup guide :bento:
solana-foundation/developer-content pull request #64
Opened 2024-02-06 09:10 UTC by heyAyushh

Added more comprehensive guide with build dependencies.

2024-02-06 09:18 UTC, heyAyushh commented
is there a way we can preview the document on the site?
I have added some images, also checked the preview on markdown VSCode extension.

2024-02-12 18:41 UTC, mikemaccana requested changes
Heya! I saw this and thought I'd spend a few minutes checking it out. There's a few minor things to fix but this looks good once they're resolved. Get a review from a DevRel person too!

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +If you are very new to development in general, or have just tried EVM based blockchains or just have fiddled with Nodejs and reactJS, your machine is not yet ready to help you code on solana.
Minor but remember to capitalize React, Node.js, Windows, etc. macOS is just macOS though according to Apple.

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +3. Install Solana cli
CLI

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +### Let’s start with Windows 8/10/11
Windows 8 went out of support on January 12, 2016

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +WSL is windows subsystem for linux, which translates Linux system calls into Windows system calls using a compatibility layer, **for running Linux binary executables natively** and it runs Linux proc
Might be too detailed. I just say "... allows you to run Linux software easily on Windows using a lightweight VM that instantly starts when you need it"

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +    [Install WSL](https://learn.microsoft.com/en-us/windows/wsl/install)
Good stuff - better to link to current instructions like you're doing than to maintain our own, out of date, set of instructions.

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +    [](https://code.visualstudio.com/docs/remote/wsl-tutorial)
Missing link text

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +```
That's not `jsx`, it's `bash`

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +    ```jsx
Again this is `bash` (it's probably zsh on a mac but `bash` syntax highlighting works)

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +    [](https://developer.apple.com/download/all/)
Missing link text

2024-02-12 18:41 UTC, mikemaccana commented on content/guides/getstarted/setup-local-development.md
> +1. Open terminal as administrator, copy and paste this command in your cmd, this downloads solana toolchain into a temporary location on C drive.
Windows uses powershell as the default shell, also I think Windows may include curl now. Not sure `cmd` is necessary.

2024-02-12 19:00 UTC, heyAyushh commented on content/guides/getstarted/setup-local-development.md
> +Rust is a multi-paradigm, general-purpose programming language that emphasizes performance, type safety, and concurrency. Or let’s just say its a coool language in boomer world.
I am sorry for this language, earlier I thought It was going on my blog, hence need a lot of reviews before.

2024-02-14 21:05 UTC, nickfrosty commented
> I don't think Windows is supported, my bad, should I remove it from this guide?
> 
> I tried it on windows 10, while the cli was installed I couldn't get a test-validator running, Idk if one of us can confirm it.

yes, windows is not currently functional. Please remove that portion from this guide. 

Also, run the prettier formatting so all actions pass: `npm run prettier:fix`

2024-02-26 06:25 UTC, heyAyushh commented
Closing this PR because I have contribute with the main branch, 
I will open new PR for this with a different branch

2024-02-26 06:25 UTC, closed without merging