Create token-explained.md
solana-foundation/developer-content pull request #77
Opened 2024-02-21 14:40 UTC by Ayushjhax

Added a detailed token-explained.md file outlining the accounts and tokens in Solana, along with an explanation of the token program. Included images for better visualization and clarity.

2024-07-25 03:07 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +This is like your main wallet where you stash your SOL coins (Solana's own
I can do a full PR review later but this won’t pass legal.

2024-08-20 17:30 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +money). It’s used to derive the accounts for your tokens.
```suggestion
This is your main wallet where you store your SOL (Solana's native token). The address of this account is used to derive the accounts for your tokens.
```

2024-08-20 17:41 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +  and instruction data."
This discription is out of date too.

2024-08-20 17:43 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +to worry about learning the complicated language of the blockchain.
I would remove this entire section. You're focusing on the different types of accounts here - talking about RPCs isn't necessary.

2024-08-20 17:45 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +account, sharing similar data and intent for performing transactions.
```suggestion
These accounts are associated with wallets and hold a balance of a specific token. Their address is calculated from the wallet account and the mint account for that particular token.
```

2024-08-20 17:49 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +who's allowed to make more, that sort of thing.
```suggestion
### Token Mint Account

The token mint account (sometimes just called a mint account) is like a factory for a specific token. It stores the supply of the token (how many tokens have been created), the mint authority (the account allowed to mint more tokens), the decimals of the token, and (if using Token Extensions Metadata) on-chain metadata about the token, like a name and symbol and URI.
```

2024-08-20 17:53 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +who's allowed to make more, that sort of thing.
Much of the information above is already included in your bullet points.

2024-08-20 17:56 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +  which the mint tokens can be frozen.
```suggestion
- **Mint authority:** a wallet or multisig account that is allowed to make (mint) more tokens.
- **Supply:** how many tokens have been issued overall
- **Decimals:** The limit until which the token can be broken down into.
- **Freeze authority:** a wallet or multisig account that is allowed to freeze token accounts.
- **Metadata** (if using Token Extensions Metadata) on-chain metadata about the token, like a name and symbol and URI. 
```

2024-08-20 17:57 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +- IMAGE
```suggestion
```

We now suggest using token extensions for token metadata.

2024-08-20 17:58 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +functionalities.
```suggestion
Tokens in Solana are created using the Token Program. This program allows users to create token mints, mint tokens, transfer tokens, and burn tokens.
```

2024-08-20 17:58 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +functionalities.
I've removed the 'factory' analogy as we use this elsewhere (not just in this document) for token mint accounts.

2024-08-20 18:00 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +### Creation and Functionality
```suggestion
## The Token Program and Token Extensions Program
```

2024-08-20 18:04 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +  forever!
```suggestion
 - Create new types of token, by making **token mint accounts**
 - Mints for new tokens (if they're a mint authority for the token mint).  
 - Transfer tokens between accounts 
 -  Burn tokens - destroy tokens forever, and get back the storage fees - often done for spam NFTs! 
```

2024-08-20 18:05 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +Program library.
```suggestion
```

2024-08-20 18:05 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +Program library.
This is redundant.

2024-08-20 18:09 UTC, mikemaccana requested changes
Sorry about the wait here and thanks for the contribution! This needs a few tweaks before it can go live. See the suggestions inside.

2024-08-20 18:10 UTC, mikemaccana commented on content/guides/intro/token-explained.md
> +to worry about learning the complicated language of the blockchain.
```suggestion
```

2024-08-21 02:03 UTC, jacobcreech commented
@mikemaccana @Ayushjhax this feels more like a blog post rather than a guide that should live on Solana.com. Given that docs already exist on token today, I'd recommend self publishing this

2024-09-06 10:46 UTC, closed without merging